
output_dir: $GCS_MODEL_DIR/planc/svhn
name: vit-b
project: jax-adv-image-net-svhn
steps: 73257
training_epoch: 6000
warmup_epoch: 50
log_interval: 100
eval_epoch: 2
grad_accum_steps: 1
use_pgd: True

resume: True

dataset:
  train_batch_size: 4096
  valid_batch_size: 1024
  train_loader_workers: 20
  valid_loader_workers: 10
  train_dataset_shards: "$GCS_DATASET_DIR/svhn-train-wds/shards-{00000..00099}.tar"
  valid_dataset_shards: "$GCS_DATASET_DIR/svhn-test-wds/shards-{00000..00063}.tar"
  random_crop: src
  color_jitter: 0.0
  auto_augment: "none"
  random_erasing: 0.0
  auto_generated_augment: "none"
  color_generated_jitter: 0.0
  random_generated_erasing: 0.0
  augment_repeats: 3
  test_crop_ratio: 1.0
  shuffle_seed: 1
  image_size: 32
  generated_dataset_shards:
    ['$GCS_MODEL_DIR/svhn_50m-1024-wds/shards-{00000..01023}.tar']
  dataset_mix_ratio: 0.1
  max_syn_ratio: 0.8
  min_syn_ratio: 0.8
  scheduler: 'stable'


train_state:
  train_module:
    target: 'train_modules.TrainAdvModule'
    mixup: 0.0
    cutmix: 0.0
    criterion: ce
    label_smoothing: 0.0
    train_adv_step: 10
    beta: 8
    eps: 8/255
    train_adv_step_size: 2 / 255


  model:
    target: 'models.ViT'
    model_kwargs:
      labels: 10
#      drop_path_rate: 0.6
#      drop_rate: 0.5

  optimizer:
    target: 'lion'
    optimizer_kwargs:
      learning_rate: 1.0e-4
      weight_decay: 0.5
      b1: 0.9
      b2: 0.99
#      eps: 1.0e-8
#      lr_decay: 1.0
#      clip_grad: 0.0


  init_seed: 1
  mixup_seed: 1
  dropout_seed: 1
  ema_decay: 0.9998
  pretrained_ckpt: None #'caformer_b36.sail_in1k'






#    --init-seed 1 \
#    --grad-accum 1 \
#    --warmup-steps $((1281167 * 5 / $TRAIN_BATCH_SIZE)) \
#    --training-steps $((1281167 * 300 / $TRAIN_BATCH_SIZE)) \
#    --log-interval 100 \
#    --eval-interval $((1281167 * 10 / $TRAIN_BATCH_SIZE)) \
#    --project deit3-jax \
#    --name $(basename $0 .sh) \
#    --ipaddr $(curl -s ifconfig.me) \
#    --hostname $(hostname)
